sudo: false
language: perl
perl:
    - "blead"
    - "dev"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18.3"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.12"
    - "5.10.0"
    - "5.10.1"
    - "5.8.4"
    - "5.6.2"
matrix:
    allow_failures:
        - perl: blead
before_install:
          - cpanm Readonly  # so t/magic-readonly.t can run
          - eval $(curl https://travis-perl.github.io/init) --auto
